# image will be published to ghcr.io/<user>/<name>
name: my-ublue
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-nvidia
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/che/nerd-fonts/repo/fedora-%OS_VERSION%/che-nerd-fonts-fedora-%OS_VERSION%.repo
    install:
      # - micro
      # - starship
      - audacious
      - torbrowser-launcher
      - neovim
      - fish
      - fastfetch
      - steam
      - dwarffortress
      - libreoffice
      - autocorr-pt
      - libreoffice-langpack-pt-BR
      - inkscape
      - solaar
      - nerd-fonts
      
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      # - firefox
      # - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
      - kate
      - kate-krunner-plugin
      - kate-plugins
      - kcharselect
      - kfind
      - krfb
      - krfb-libs
      - kwalletmanager5
      - firewall-config
      - kdebugsettings
      - kjournald
      - kjournald-libs
      - vim
      - vim-enhanced

  - type: brew
    auto-update: true
    auto-upgrade: true

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      # repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      # repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        # - org.mozilla.firefox
        # - org.gnome.Loupe
        # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
      # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),
      # only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Installing different branches of the same Flatpak is not supported.
      - com.github.Anuken.Mindustry
      - com.github.wwmm.easyeffects
      - com.heroicgameslauncher.hgl
      - com.obsproject.Studio
      - dev.vencord.Vesktop
      - md.obsidian.Obsidian
      - org.gimp.GIMP
      - org.kde.kdenlive
      - org.keepassxc.KeePassXC
      - org.localsend.localsend_app
      - org.prismlauncher.PrismLauncher
      - org.qbittorrent.qBittorrent
      - io.mpv.Mpv
      - org.kde.gwenview
      
      remove:
      # - org.gnome.eog

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

